# @Time : 2022/5/10 14:46
# @Author : Zhichen Lu
# @File : FactorCategory.py
perfect_distr = [
    'MinCorrExcessPriceRank', 'FactorAlpha007', 'CorrCloseVol_Mean_1', 'HighTurnVwap', 'VolSkew', 'OverBuySellKurtRank_1_5',
    'LowHighStdRatio', 'VwapmaLowDiffSkew_13h',
    'RetToStd', 'FactorMin1_diff_div_std', 'HF_VwapTailTRRatio_13h', 'VolSharpeUp_13h', 'HfLast120HighLowDiffAmtCloseCorrPreBias',
    'HF_Shortcut2CloseCloseCorrZscore',
    'UpDownVolRatioStdRaw_1_1', 'HighLowStdRatio_mean5d', 'CorrCloseVol', 'UpDownVolRatioSkewRank_1_1',
    'VolRatio10min', 'FactorMin27_std', 'CorrVWAPstd', 'amtavg_bwmaxskew_60_3', 'CorrVWAPdt', 'HF_TwapRetWeightSkew',
    'VolumeMax10min2All_13h', 'DisPSkew_1', 'Smartmoney_ret_min_02_05_rolling3', 'RetAdjVolMaxRank_1_5',
    'VolumeUpPVCorr_13h', 'HfLast120HighLowDiffAmtCloseCorrDelta_13h',
    'AggressionNRank_5_1', 'MinCapitalGainAbs', 'hfHighVolPVcorr', 'uretvvolnew_bwskewmean_60_3',
    'HighFreqWaveRetStd',
    'FactorMin13_diff', 'IndustryExcessPVCorrBias5d', 'FactorAlpha027', 'CorrVwapCVPriceLast60',
    'uretvvolnew_bwskewmean_60_10',
    'AmountMktDiff', 'FactorMin81_diff_div_std', 'RS_mean', 'AbnormalVolumePVCorr', 'VwapSkew5mean',
    'HF_5mRePosVolVolatilityStable',
    'WAPResistBackRatio_13h', 'FactorMin13_diffdivstd', 'hfCPVCorrHD_13h', 'HF_VolSwing5mToAll',
    'dretvvolnew_bwminskew_60_10',
    'LowStdAmountRatio', 'DisNSkew_5', 'HighFreqDrawBack', 'CloseVolumeCorrBias20d', 'CloseCorrVolume_5',
    'CumSwingCumAmountDiffSharpe', 'Rsrs', 'FactorMin217_mean_re', 'MinPre30mAutoCorr', 'SkewUpDown', 'hfPVcorrHD',
    'RetUpSkew_Mean5', 'Last30MaxClimbBias20d', 'FactorMin218_diffdivstd', 'hfHVRbias', 'HighFreqTurnRetCorr', 'HighFreqDrawBackMeanBias',
    'PVSwingCorr', 'SmartVwapSharpe5d', 'uretvolnew_bwskewtb_60_10', 'RetVolCVMultiple', 'CloseVwapRetSkew',
    'HfSwingCloseCorr', 'amtavg_bwskewmean_60_10', 'HF_HmL2CVwapCorr_13h', 'FactorMin87_diff', 'FactorMin150_diff',
    'VolMeanSharpeUp2Down', 'PriceUpDownRatio', 'HF_PriceDiffStdRatio', 'HF_UpRetAmtSkew', 'EVolChgSkew_1_30',
    'CorrAmpVwap_1', 'HfLast120HighLowDiffAmtCloseCorrSharpe', 'FactorAlpha024', 'uretvvolnew_ntdmkurt_20_10',
    'HF_RSRSZScore', 'HF_RetTopVwapAmtCorrBias', 'MinCapitalGainRH', 'Last30MaxDrawdownBias20d', 'HF_VwapTailVolumeRatio_13h',
    'HFPSCorrMin', 'FactorMin405_std_re', 'FactorMin10_meandivstd', 'uretvvolnew_bwtbkurt_20_10', 'hfDownPVcorr5',
    'HF_VwapStdSwingCorrZscore_13h', 'FactorMin80_diff', 'CorrPVLowLiquidity', 'MeanRatio_min5', 'FactorMin22_std',
    'VolaRatio10Mean', 'WAPResistBackTop_13h', 'HfLast120CloseVolumeStdCorrBias_13h',
    'HF_MeanIntradayReturnAcrossProfitableInvestors_13h', 'dretvolnew_bwskewmean_60_10', 'PVRatioCorr', 'FactorMin155_mean',
    'RetAdjVolSkewRaw_1_1', 'RetAdjVolSkewMean_1_1', 'StdRatio_min5', 'HF_HmL2CVwapCorrZscore_13h', 'amtavg_bwskewmean_60_3',
    'CorrHighLowAvgToAmt_Mean_1', 'amtavg_ntdmkurt_20_10', 'hfUpRRC', 'HF_Amt10mSkew20d', 'dretvvolnew_bwskewmean_60_10',
    'MACDNumDiffBeta_5_5', 'FactorMin168_std', 'MinDailyCorrCloseVol', 'UpDownAmtRatioStdStd_3_5', 'HFPVCorrBias', 'RSRS_Mean_1',
    'HFPSCorrStdAdj', 'AbnormalReturnPVCorrBias20d', 'HFPTSCorrStdAdj', 'HF_AmtDeg1', 'HF_RSRS', 'HfLast120RtnStdCloseCorrBias',
    'HF_VolumeStrengthDeg1', 'WRMean5d_13h', 'MinPrePriceRate', 'Factor_Fix_zhy_208', 'HF_VwapTailTopTRRatio_13h',
    'HF_VwapTailTurnRatioZscore',
    'Smartmoney_close_max_005_05_rolling3', 'DisPRegbeta_5', 'HF_LowReBiasSelfCorrStable_13h',
    'HF_AmtVolatilityPriceCorr_13h', 'FactorMin31_std', 'CorrMaxRePriceRank', 'FactorMin285_std_re', 'HF_Last30mBiasVolumeCorr_13h',
    'PriceMktDiff', 'HighLowMeanVwapRetSharpe', 'HF_VwapAmtUpCorrInLowVolatility_13h', 'CorrExcessRank2',
    'HF_VwapTailTopTRRatioMin_13h', 'amtavg_mktstate_amt_std_topskew_5_3', 'FactorMin14_diff', 'MinPrePriceAutoCorr',
    'HF_LinearHighDiffSkew_13h', 'HighFreqVolumeMACmp', 'ReLow_13h', 'Smartmoney_hlratio_max_02_05_rolling3',
    'CloseOneOrderTwoOrder', 'HLM4_zhy', 'MinPre30mAutoCorrDelta', 'DisNRegbeta_5', 'HF_OpenVwapSkew',
    'HfHalfDayCloseRtnCountDiff_13h', 'DIFMeanRegbeta_5_30', 'DrawdownSkew', 'SkewDuringAmountHike', 'RSIMeanRegbeta_5_15',
    'amtkrt_bwmeantb_20_10', 'MaxDrawDown', 'HF_AmtStdStrengthDev_13h', 'MinuteVolatilityPriceCorr', 'VwapStdCorrBias20d_13h',
    'LargeSmallVolumeVWAPRatio', 'MinCapitalGainOverhang', 'HF_Hl2OStrength_13h', 'hfUpPVcorrbias', 'DisPStd_1', 'CorrVwapVol_1',
    'DisNMean_1', 'UpToRetValue', 'Factor_Fix_zhy_101', 'uretvvolnew_ntskewmean_20_3', 'HF_VwapTopTRRatio_13h',
    'HF_VwapLowCorrZscore_13h', 'HF_VwapTopTailTurnRatioZscore', 'HfLast120RtnPerAmtVolCorr', 'WR2d_13h', 'MinVwapHLRateBetaBias',
    'HfLast120MinRtnCloseCorrBias', 'DisNStd_1', 'HFPVCorr', 'HF_WR2d', 'MinExtremRet', 'TurnHighSkew',
    'HF_NormRePriceCorrSharpe_13h', 'HF_LinearDiffStdRatio_13h', 'dretvolnew_bwtrbmean_60_3', 'uretvvolnew_bwminskew_60_10',
    'HF_CorrMaxVolumeZScore_13h', 'HF_CorrMaxVolumeZScore_13h', 'FactorMin35_diff', 'FactorMin311_std_re', 'MinCorrVolumePrice_1',
    'DIFMaxRaw_1_5', 'HfLast120MaxRtnCloseCorrBias_13h', 'FactorMin143_meandivstd', 'CumAmountVarKurt', 'amtavg_bwskewtb_20_10',
    'FactorMin155_meandivstd', 'HF_AmtStrengthCloseChange_13h', 'CorrRankCloseVolume_5', 'HF_AmtStdStrengthCloseBias',
    'HF_VmL2HmVStdRatio',
    'MinCapitalGainBetaZscore', 'Smartmoney_close_max_02_05_rolling1', 'HF_AmtStdStrengthCloseChange_13h', 'CorrAbsWRPrice5min',
    'HighFreqDownSpeed', 'GTJA2', 'PriceSkew', 'HF_UpVolumeSkewSeasonalBias', 'CorrWRPriceRank', 'HF_HighPinZscore_13h',
    'FactorMin18_meandivstd', 'FactorMin157_diff', 'HFPSCorr', 'uretvolnew_bwskewmean_20_3', 'uretvvolnew_bwkurtskew_20_10',
    'WilliamsPriceVolCorrMultiple_13h', 'CumPVRatioCorr', 'UpDownAmtRatioSkewSr_1_5', 'HF_UpRetTurnDiffSharpe',
    'TopAmountRatioVolumeDiffSharpe', 'HF_VwapLowHighStdVolumeRatio_13h', 'TwapSkewToVwap', 'CorrHighVol',
    'HfHalfDayCloseRtnCountDiffBias_13h', 'MinPriceBeta', 'FactorMin25_std', 'HF_VwapHighStdVolumeRatioZscore_13h',
    'MinCorrVolumeRetUp_1', 'MinPriceAutoCorr', 'HfTurnMaSkew', 'uretvvolnew_ntminkurt_20_10', 'IdeaVStd', 'FactorMin32_mean',
    'HighLowStdBias20d', 'dretvolnew_bwskewmean_20_3', 'HFPTSCorrBias', 'AmountGrowthDuringLowRet', 'Factor_Fix_zhy_66',
    'hfHighVolPVcorrbias', 'MinCapitalGainAutoCorr', 'IndexCloseCorr',
    'HFPVCorrStdAdj', 'FactorMin124_diff', 'UpDownVolRatioSkewRank_3_5', 'IdealSwingMin2D', 'amtavg_bwkurtskew_20_10',
    'HfLast120RtnPerAmtVolPre1minCorr', 'MinCorrAbsRePriceRank2D', 'FactorMin221_std', 'HF_CMExcessRetWeightSkew_13h',
    'StdUpDown', 'FactorMin129_diff', 'HfLongVwapSwingCorrBias', 'hfCPVCorrHDbias_13h', 'VwapSwingCorr', 'MinVwapHLRateBetaDelta',
    'HF_VwapTopVolumeRatioZscore_13h', 'HF_RetHHIZscore', 'PriceDeviationBias10d', 'MinCapitalGainBetaEwm', 'HFPSCorrBias',
    'HF_Last30minUpVolumeRetZscore_13h', 'HFPVCorrMin', 'DivergWinLossRStdSkew_1_5', 'HF_CorrBuyStrength_13h',
    'UpDownAmtRatioKurtSr_3_5', 'HighFreqVHFCorrBias', 'HfLast120VolumeStdSkew', 'AmtPct_Mean_1', 'CloseExcessPercent_1',
'WilliamUp_diffstd5'
]

OK_distr = ['FactorAlpha040mean', 'hfCapStdRatioMin', 'BigSmallRetCloseDiff3_trans0p25', 'Min10ReUpLast5Min',
            'DisPSr_1', 'HfLast120MinRtnCloseCorrSharpe', 'HfLast120MinRtnCloseCorrSharpe', 'RetAdjVolMeanRank_3_5',
            'InflowOutflowDiff', 'er_percrank_raw_std_short', 'TrendStrength', 'dretvolnew_bwmeanskew_20_10',
            'hfHighCapRetMean', 'FactorMin370_std_re', 'RetVolStdSr_1_1', 'uretvolnew_bwskewmean_60_10', 'DivergWinLossRStdSr_5_5',
            'FactorMin13_std', 'subrr2adjwms_intraday_5', 'FactorMin89_diff', 'RetAdjVolStdSkew_1_5', 'Smartmoney_close_max0505_rolling1',
            'VolBurstReturn', 'RetAdjVolStdRegrmse_5_1', 'amtkrt_nttbmean_20_3', 'CorrLowVol_mean5', 'MinPVCorr', 'FactorMin47_std',
            'CorrVolumePriceRankSharpe',
            'ShortTurn', 'VolChg1Mean', 'HighLowStdRatio_meandivstd5', 'ConsRetStd3std', 'HighSkew_Mean_5', 'DivergWinLossRStdRegrmse_1_5',
            'StdMaxAmountRatio', 'uretvvolnew_ntminkurt_60_10', 'FactorMin339_std_re', 'GTJA5', 'FactorMin343_mean_re', 'HfLast60TurnVolCorr',
            'dretvvolnew_ntskewmean_20_3', 'hfMktLSCapSR', 'SignDownWick', 'FactorMin362_std_re', 'AmtStd_Mean2Std_5', 'zhy_fix_146',
            'hfIdxCorr',
            'HF_VwapTopTailVolume_13h', 'AggressionNRank_5_5', 'GTJA53_ts_rank5', 'HLLength5', 'UpDownAmtRatioStdMean_1_5', 'FWRMin',
            'adjEMAbc_intraday5', 'VolumeStd_Mean2Std_5', 'DisPRaw_5', 'GTJA62', 'HF_VwapTailTopVolumeDiffRatio_13h', 'DisNRaw_5',
            'RetToVolSke',
            'MinVRCExcess_13h', 'DIFDifSr_1_1', 'er_percrank_raw_std', 'TurnHighKurt', 'zhy_fix_73', 'FactorMin289_std_re', 'GTJA7_mean5',
            'DIFSkewMean_1_1', 'FactorMin89_std', 'VHighKurt', 'GTJA16_min5', 'AggressionPRaw_5_1', 'TurnWeiRet3min', 'WR_13h',
            'FactorMin450_mean_re', 'HF_VolumeSharpe', 'StdAmountDiff', 'MinPreTopVolRate', 'Rtn2VolumeMeanAbs1', 'OverBuy_Mean_5',
            'HF_CloseVwapSkew_13h', 'FreeTurn_Mean_1', 'WilliamsIndicator_13h', 'LowRetAmountSkewRatio', 'MaxAmtStdRatio', 'CORA_R_3',
            'FactorMin335_std_re', 'dretvvolnew_ntmeanskew_60_10', 'HighLowStdLowDistance10d', 'RetVolMaxRaw_1_5',
            'uretvolnew_nttbkurt_60_10', 'Excess300High5', 'Smartmoney_volume_skew_005_05_rolling1', 'HF_OverBuySell_13h',
            'HLStdRatio', 'HLStd1mean', 'HighFreqHighMARetCorrSharp', 'Smartmoney_close_dm_02_05_rolling3', 'FactorMin403_mean_re',
            'OverBuySellKurtSr_5_5', 'HfLast120MaxRtnCloseCorrSharpe', 'UpCountLowDistance10d', 'FactorMin343_self_re', 'HF_OverBuy',
            'HF_HDeg1_13h', 'VwapStdCorrDistanceLow10d_13h', 'amtavg_bwstdskew_20_3', 'FactorMin285_self_re', 'HighLowVwapRatio',
            'FactorMin430_mean_div_std_re', 'HF_AmtVolatilityPriceCorr5D_13h',
            'RetAdjVolMeanSkew_1_5', 'FactorMin353_std_re', 'HF_PriceDiffRatio', 'HF_VmL2HmVStdRatio10minBias', 'amtavg_bwtbkurt_60_10',
            'Excess500Low5', 'FactorMin405_mean_div_std_re', 'hfRST', 'HF_VwapLowVR_13h', 'OverBuy_Mean_1', 'VolumeDownChange_13h',
            'AmtSkew3', 'PVRatio10trans0p5', 'StdDelayRatio', 'Close2High', 'VwapBollingerBand30min_13h', 'RetVolStdSkew_1_1',
            'IdeaVKurtReg', 'RetVolMinSr_1_1', 'HF_VwapBollingUp_13h', 'FactorAlpha024dif', 'GTJA8', 'HF_IlliqShortcut_13h',
            'FIX_lly_8', 'MinAmtStdRatio', 'FactorMin32_mean_div_std', 'LowSharpeAmountStdRatio',
            'EVolChgSkew_1_1', 'HF_VwapTopTailAmtRatio_13h', 'HighFreqSwingStdCmp', 'BottomTopPriceSwingRatio', 'HighCloseDistance',
            'AmtPct_regrmse', 'HfRtnPerAmtVolCorr', 'NewCorrHighVol', 'IntradayAmountRatio', 'AvgStdRatio_min5', 'HighFreqDrawBackStdBias',
            'HighLowVwapDiffStdRatio', 'High2LowVolDown', 'FactorMin28_std', 'HighFreqLowRetCorr', 'FactorMin48_mean_div_std',
            'CorrAmpAmt_1', 'HF_DVwapDVolumeCorrZscore_13h', 'amtavg_ntminkurt_60_10', 'FactorMin124_meandivstd',
            'FactorMin118_meandivstd', 'FactorMin283_std_re', 'FactorMin93_mean_div_std', 'GTJA32', 'AmtKurt',
            'HF_CloseLowHighStdVolumeRatio_13h', 'HighStdRatio_min5', 'dailyms_intraday_5',
            'CorrCloseVol_Mean2DStd_5', 'amtavg_ntskewtb_20_10', 'RSIMeanRegrmse_1_15', 'HF_VolumeStrengthCloseStdBias', 'uretvvolnew_ntskewmean_60_3',
            'dretvolnew_ntrdmmean_60_3', 'FactorMin157_diffdivstd', 'HfLast120LongTurnSkew_13h', 'SplitVolumeRatio', 'DivergWinLossRMaxSkew_1_5',
            'dretvvolnew_bwmeanskew_60_10', 'cummaxdd_nttrbmean_20_3', 'RetVolMaxSkew_1_1', 'FactorMin124_diffdivstd', 'HF_LDeg1_13h', 'AbnormalPriceDiff',
            'hfLowCapRetMin', 'CorrResisVWAP', 'PDS', 'VolMeanSharpeUp_13h', 'RetToVolabs', 'RawAmtStdRatio', 'hfDownPVcorrbias',
            'FactorMin224_meandivstd', 'CorrVWAPBollingUpDown', 'RetVolMaxSkew_1_5', 'VwapBollingerBand_13h', 'VRSS', 'IdealRev2',
            'InstitutionalVolumeRatio2min', 'hfDownStrength', 'FactorMin28_mean', 'SharpeDuringStdDrop', 'HF_ReverseVolRatioVWAP',
            'SharpeDuringAmountDrop', 'MinDirectedVol', 'amtavg_mktstate_ret_topskew_5_3', 'RollingCorrCloseVolume',
            'HF_PriceVolIndustryDelta', 'hfMktLSCap', 'FactorMin214_mean_div_std_re',
            'DIFMaxSr_1_5', 'Smartmoney_hlratio_max_05_05_rolling1', 'SwingPerDeal', 'HighFreqRelativeClose', 'CorrLowVol_min', 'adjstdwms_intraday_5',
            'UpVolatilityRate', 'amtkrt_ntrdmmean_20_10', 'zhy_fix_112', 'AggressionPRaw_3_5', 'HighFreqTurn', 'StdRatio_max5',
            'CSAD5std', 'RetTurnCorr','HighLowVwapRatio','AvgClose2Vwap_Mean2Std_5','Smartmoney_amt_kurt_02_05_rolling1','CorrVWAPTrendHigh',
            'FactorMin53_mean_div_std','FactorMinVaR_regrmse_05_10'

            ]

to_diff = [
    'FactorMin289_mean_re', 'FactorMin81_std', 'FactorMin159_std', 'RollingCloseOpenWeightedCorr_10', 'HighFreqRetRefStd',
    'FactorMin33_mean', 'AmtPcg_regrmse', ''
                                          'FactorMin70_diff', 'HLStdRatio_min5', 'PriceVolume_5', 'amtkrt_ntrdmmean_60_10',
    'HighFreqHighMARetCorr', 'FactorMin93_diff', 'VolumeStd_Mean_5', 'HLOKurt3', 'FactorMin150_mean',
    'RetStd_Mean_5', 'FactorMin163_mean', 'FactorMin215_meandivstd', 'FactorMin215_mean', 'FactorMin137_mean',
    'FactorMin94_mean', 'DIFMeanRaw_5_30', 'FactorMin160_mean', 'hfIdxCorr5', 'VolumeStd_Mean_1', 'FactorMin153_std', 'DIFMaxSr_1_1',
    'LogRtn2Amt5', 'adjstdsd_intraday_5', 'DivergWinLossRMaxStd_1_5', 'RetVolSkewMean_1_5', 'SwingPriceLongCorr', 'DIFStdSr_5_1',
    'HF_TurnoverrateStd', 'amtavg_ntskewmean_60_3', 'DivergWinLossRSkewMean_5_5', 'SwingReturn', 'OverBuySell_Mean_5',
    'FactorMin37_mean',
    'GTJA14_std5', 'FactorMin193_mean_re', 'StructedRev5', 'MaVolDistance10', 'FactorMin72_mean', 'RSJT', 'Ret30RankMean_5',
    'CorAmtStdSKew5',
    'RetAdjVolSkewSr_3_5', 'FactorMin61_mean_div_std', 'TurnHighStd_meandivstd', 'TurnHighSkewRollingReg', 'CorAbsRetVol3',
    'RetVolMaxSr_1_5', 'Cor300Up5mean', 'Factor_Fix_zhy_15', 'NetworkPremium3', 'DivergenceStdRaw_5_15', 'AggressionNMean_1_1',
    'dretvolnew_ntkurtmean_20_10', 'MinPrePVCorr', 'Smartmoney_amt_ms005_05_rolling3', 'AccelerateSkew', 'FactorMin161_std',
    'Excess500High5', 'BSPowerSkew3mean', 'IdeaVStdMax', 'TurnStdPure3mean', 'HF_VwapTopTailVolumeStdRatio_13h', 'RevExclu4mean',
    'CorrRetVol_5', 'dretvolnew_ntdmstd_60_10', 'WeightedFlow_1', 'FactorMin77_std', 'FreeTurn_Mean_5', 'AmtStd_Std_5',
    'MACDNumDiffMean_5_5', 'HLStdRatio_max5', 'TurnFree_3', 'MinDailyCorrCloseVol_min5', 'RSIStdRank_5_5', 'HighLowStdRatio_min5',
    'AbsRet30Mean_5', 'HfLongVwapSwingCorr5d', 'adjdmstdcpt_intraday_5', 'FactorMin13_mean', 'BI500Std5',
    'dretvvolnew_ntskewskew_60_10', 'AccelerateStdRE_std10', 'OverBuySellSkewRegbeta_5_5', 'LogDeltaVol', 'TurnWeiRet3max',
    'StableRet20', 'StdHmL_20', 'High2Low_5',
    'UpDownVolRatioStdRegbeta_5_5', 'uretvolnew_ntstdskew_60_10', 'MinUpDownVolRet', 'HfTopRtnVolumeRatioMean', 'FactorMin75_mean',
    'FactorMin162_mean', 'dretvolnew_ntminstd_20_10', 'HfSwingCloseCorrSharpe', 'amtavg_ntminskew_60_10', 'LogRtnAbs2Amt1Res',
    'sistdwfiavg2_3_re', 'LogDeltaVol_meandivstd10', 'GTJA16_max5', 'DivergWinLossRMeanStd_5_5', 'FactorMin117_mean',
    'CloseOpenSkew2Abs', 'CGO', 'cummaxdd_bwmaxstd_20_10', 'hfDownTurnSharpe', 'amtavg_ntskewmean_60_10', 'AmtPct_Mean_5',
    'FactorMin95_mean', 'AmtStd_Mean_1', 'uretvolnew_ntskewmean_60_10', 'Min1WeightedFlow_1', 'CRCS_raw_rank_skew10',
    'WeightedFlow_5', 'FactorMin26_std', 'OverflowPerAmtMean5d', 'RollingCloseOpenWeightedCorr_5', 'FactorMin151_std', 'LogFreeTurn_5',
    'FactorMin82_mean', 'dretvvolnew_ntstdskew_20_10', 'UpDownAmtRatioSkewSr_5_30', 'MACDEChgStd_5_1', 'dretvvolnew_ntscmskew_20_10',
    'IdeaVStdL_mean10', 'uretvvolnew_nttbkurt_20_10', 'DivergWinLossRStdStd_5_15', 'hfTurnSharpeHD', 'CloseVwapRetKurt',
    'FIX_lly_7', 'VolCorr', 'IdeaVL', 'FactorMin15_mean', 'Beta300', 'FactorMin165_std',
    'MinPre5mSkew', 'HF_CorrCloseVolumeSharp_13h', 'amtavg_ntstdskew_20_10', 'CorAmtStdStd5', 'OCKurt3mean', 'IdeaVStdReg',
    'dretvvolnew_ntscmmean_60_10', 'RetVolSkewRaw_5_1', 'RetStd_Mean_1', 'GTJA43_min5', 'RetMean_Rank',
    'dretvolnew_ntminskew_60_10', 'High2Low_1', 'RollingRetCorrPctg_5', 'FactorMin157_mean', 'RegAccelerateStd',
    'uretvvolnew_bwmeanskew_60_10', 'HLTR_mean5_intraday', 'TurnVolatilitySharpe5d', 'CyqHhi', 'LowStdRatio_max5',
    'FactorMin127_std', 'OTC5std', 'UpDownVolRatioStdRegbeta_5_1', 'Ret30Mean2Std_10', 'IndustryExcessReturnStd5d',
    'CRCS_raw_rank_ms10', 'UDContrast5mean', 'DIFSkewRank_5_1', 'NewCorrHighVol_meandivstd5', 'IdeaVStdL_meandivstd10',
    'RetAdjVolMinRegrmse_3_5', 'dretvvolnew_nttbskew_20_10', 'TurnHighKurtRollingStd',
    'HF_TurnoverrateSharp', 'hfUpPVcorr5', 'PriceVolume_10', 'TemporalVolumePriceCorr', 'IbsLast15Min', 'sistdwfiavg_re',
    'OverBuy_Sell_3', 'FactorMin80_std', 'MACDNumChgSignRank_5_1', 'RetKurt5', 'NetworkDegree3Net', 'VarResampleMeanL',
    'cummaxdd_nttrbskew_20_10', 'uretvolnew_ntdmstd_20_10', 'VwapStdRatio_max5', 'NetworkDegree3', 'Cor500D3', 'hfHighVolPVcorr5',
    'FactorMin189_std', 'FactorMin6_mean', 'GTJA48', 'dretvvolnew_ntskewmean_20_10', 'FactorMin157_meandivstd', 'FactorMin81_mean',
    'UpDownAmtRatioKurtSr_5_5', 'TurnStdPure5std', 'SMUp0p9Vol5', 'HighFreqRetRefMax', 'Cor300Down5mean', 'DisNMean_5', 'UpdownToStd',
    'AmtRatio_Mean_5', 'PDSS', 'FreeTurn_Std_5', 'AvgStdRatioRE_regrmse10', 'uretvvolnew_ntminskew_60_10', 'RollingSignDownWick',
    'dretvolnew_bwskewtb_20_10', 'FactorMin417_std_re', 'amtavg_ntskewmean_20_3', 'RetBigStdResAmt5', 'FactorMin236_std',
    'HfLast120HighLowStdRatioMin_13h', 'RetAdjVolDifStd_1_1', 'amtavg_ntmeanskew_60_3', 'Ret30Std_5', 'HighFreqVolumeSwingCmp',
    'HfVolSkew', 'uretvvolnew_ntskewmean_60_10', 'LogFreeTurn_1', 'AccelerateStd', 'SwingPriceShortCorr', 'OverBuySellStdStd_5_15',
    'HLStd5std', 'CorrAmpAmt_5', 'uretvvolnew_bwskewmean_20_10', 'zhy_fix_5', 'uretvvolnew_bwmaxskew_20_10',
    'dretvolnew_ntkurtskew_20_10', 'PVComb5', 'FactorMin8_mean', 'FactorMin98_mean_div_std', 'BestWorstReSharpe5d',
    'NormalCloseAmtCorrDecay10d', 'GTJA20_std5', 'CloseOpenKurt2Mean5', 'FactorMin165_mean', 'HF_ForecastEPDelta40d',
    'TurnVolatilityStd5d', 'LiqUp5', 'Min1WeightedFlow_5', 'AmtStd_Mean_5', 'AmtStdRet_mean10', 'AggressionPMean_3_5',
    'OpenDivClose_5', 'uretvvolnew_ntkurtskew_20_10', 'CorrAmpRet_5', 'GTJA1_6', 'dretvolnew_bwkurtmean_20_10',
    'AggressionPMean_5_5', 'RetAdjVolMeanRaw_5_30', 'FactorMin42_mean', 'VarResampleMean_max10', 'amtavg_bwmaxskew_60_10',
    'FactorMin1_std', 'TurnWeiRet5min', 'amtavg_ntmeanskew_60_10', 'RetGather0p9mean5', 'CorrRankOpenVolume_10',
    'AvgStdRatio_mean5', 'uretvolnew_ntkurtmean_20_10', 'FactorMin18_mean',
    'VwapmaDiffVolCorr_13h', 'DivergWinLossRStdRegbeta_5_15', 'HighVStd_meandivstd10', 'FactorMin35_std', 'CorrVwapVol_5',
    'FactorMin200_meandivstd', 'AvgStdRatio_max5', 'FactorMin1_mean', 'RetVolMeanSr_5_1', 'CSAD5mean', 'RetRightTail',
    'DivergWinLossRMinStd_1_5', 'hfCPVCorrHDmean_13h', 'FactorMin7_mean', 'FactorMin43_std', 'TopAmountTradingCostRatio',
    'uretvolnew_ntmaxstd_60_10', 'MACDNumDiffMean_1_1', 'RetAdjVolMeanRegbeta_5_30', 'RetAdjVolMaxMean_1_5',
    'uretvolnew_ntmeanskew_60_10', 'FactorMin66_mean', 'amtavg_bwskewmean_20_10', 'TurnoverHighRetSharpe', 'VolaRatio5Std',
    'FactorMin162_std', 'hfUBstd', 'CORA_A_3', 'VwapStdRatio_min5', 'FactorMin384_mean_re', 'FactorMin235_std',
    'PriceRange_5', 'hfDownPVcorrsharpe', 'RSRS_Mean_5', 'BiasStd3_5Std', 'LogRtn2Amt1Res', 'CorAmtMeanSKew5',
    'adjstdstm_intraday_5', 'CorrDelVolumePriceMean', 'FactorMinKdayShortCut_std', 'SignedVolume', 'FactorMin83_mean', 'VWMidReurnSharpe5d',
    'GDZQ4std3', 'AggressionPStd_5_1', 'cummaxdd_ntmaxstd_20_3', 'uretvolnew_bwkurtmean_20_10', 'CorPV5', 'MinDailyCorrHighVol_std5',
    'hfHVR5', 'Smartmoney_volume_skew_02_05_rolling3', 'RetAdjVolMeanRegrmse_1_1', 'WeightedTurn_10', 'DIFMeanRaw_5_5', 'firstintraretskew5_re',
    'EVolChgStd_5_5', 'L2C5', 'HighStdRatio_max5', 'UpDownAmtRatioStdRegrmse_5_5', 'FactorMinKdayShortCut_regrmse', 'FactorMin116_std',
    'FactorMin70_mean', 'VwapStdRatio_mean5', 'LatestRetRatio', 'FactorMin79_std', 'DivergWinLossRDifStd_1_5', 'IndustryExcessIlliqSharpe5d',
    'RetVolMaxSr_1_1', 'CloseSkew_Mean_5', 'AggressionNMean_3_5', 'uretvolnew_bwmaxskew_60_10', 'StableVol5', 'FactorMin164_mean', 'StableVol20',
    'HF_PriceVolCorrIndusRank', 'MACDNumDiff_5_5', 'RetVolStdSr_1_5', 'HF_AmtStrengthCloseSharp_13h', 'FactorMin171_meandivstd',
    'DivergWinLossRStdSr_1_5', 'FactorMin201_mean', 'FactorMin73_std', 'TurnWeiRet5mean', 'FreeTurn_Mean2Std_5', 'amtavg_ntscmmean_60_10',
    'amtavg_ntdmkurt_60_10', 'GTJA40', 'Vwap2Twap5mean', 'FactorMin3_std', 'FactorMin40_std', 'EVolChgBetaAbs_1_1', 'dretvvolnew_bwstdkurt_60_10',
    'amtavg_ntminskew_20_10', 'Factor_Fix_zhy_205', 'DIFStdRegbeta_5_1', 'amtavg_ntkurtskew_20_10', 'HLSkew5mean', 'UpVolatilityRateStd5d',
    'FactorMin26_mean', 'subrradjwms_intraday_5', 'GTJA8_mean5', 'hfUpRRCbias', 'TurnWeiRet10slope', 'GTJA43', 'CorrMaxRePrice5minSharpe',
    'TurnWeiRet5max', 'MinuteTVRtnRank', 'dretvvolnew_ntminskew_20_10', 'hfHighVolPVcorrsharpe', 'DIFSkewMean_5_5', 'AvgClose2Vwap_Std_5',
    'GTJA27_max12', 'OverMean_Std', 'AccelerateStdRE_meandivstd10', 'TurnWeiRet3mean', 'Smartmoney_amt_skew_05_05_rolling3',
    'CorrAmpVwap_5', 'uretvvolnew_ntkurtstd_20_10', 'DivergWinLossRMeanRank_5_5', 'LogAmt_5', 'VolaDownward20', 'hfTurnStdHD',
    'Rtn2VolumeStd5', 'MinPreVolRet', 'FactorMin12_std', 'MACDNumDiffBeta_5_1', 'FactorMin53_meandivstd',
    'DivergWinLossRStdRegrmse_5_5', 'DIFMeanSr_5_5', 'HfVolClosePre5minCorr10d', 'RetAdjVolSkewRank_5_30',
    'VwapAmtCorrMean5d_13h', 'amtavg_bwstdkurt_20_10', 'LogAmt_1', 'AvgPriceVwapRateStd5d', 'MinMaxRet', 'VolGather0p9mean5',
    'GTJA27_weight12', 'CorAmtMeanMean5', 'VolumeStd_Std_5', 'HFPVCorrMean', 'FactorMin166_std', 'amtavg_ntmeankurt_20_10',
    'CPV10', 'HF_VolumeTopVwapRatio', 'FactorMin10_std', 'RetVolSkewMean_5_5', 'cummaxdd_nttrbmean_20_10',
    'HF_UpReaturnRealStdZScore', 'RetAdjVolSkewRegbeta_5_5', 'FactorMin35_mean', 'AbsRetDivFreeTurn_5', 'FactorMin45_std',
    'HighV_meandivstd10', 'FactorMin33_std', 'HfAmtSpaceSkewMean_13h', 'DIFDifSr_1_5', 'FactorMin218_meandivstd',
    'HfLast120CloseSwingStdCorrSharpe_13h', 'FactorMin193_std', 'RetUpWeightedByVolSR', 'SwingPriceCorr', 'hfMktLSCapMR5', 'FIX_lly_12', 'DivergWinLossRMinMean_1_5',
    'Vwap2TwapKurt5std', 'HFPSCorrMean', 'FactorMin2_std', 'Close2BarHigh', 'RetAdjVolStdRegrmse_3_5',
    'dretvvolnew_ntstdkurt_20_10', 'hfUpTurnSharpe', 'HLSkew5std', 'MinDailyCorrHighVol_max5', 'Beta500d3', 'FactorMin453_std_re',
    'OverBuySellStdStd_5_5', 'WL350_5', 'Last30minReVolumeCorrMean5d', 'uretvolnew_bwstdskew_60_10', 'FactorMin87_mean_div_std',
    'dretvolnew_ntmeanskew_20_10', 'DisPMean_5', 'FactorMin72_std', 'TurnStd', 'dretvvolnew_ntskewmean_60_10', 'RetVolMeanSr_1_1',
    'uretvvolnew_ntmeanskew_20_10', 'RetAdjVolMeanSr_1_5', 'FWRM', 'RSIMinMean_1_15', 'FactorMin76_mean', 'AmtStdStd5d',
    'CorrHighLowAvgToAmt_Mean_5', 'CorrCloseVol_Mean_5','AbnormalReturnPVCorrMean20d','Smartmoney_close_max0505_rolling3'

]

trend_dirift = ['GTJA54G', 'GTJA54_N', 'FSmartMin', 'FSmartMax']
drop = ['FactorMin229_mean_div_std_re', 'HF_MeanIntradayReturnAcrossLosingInvestors_13h', 'HFPVCorrMinAdj']
kind_of_prob = ['GTJA41', 'FactorMin447_self_re', 'uretvvolnew_bwmstb_20_10', 'VolumeVarianceRatio_13',
                'HF_VolumeAmtSkewRatio', 'HF_VwapRetSkew_13h', 'dretvvolnew_ntmsmean_60_3', 'RetUpSR', 'SplitStdRatio',
                'Smartmoney_hlratio_kurt_05_05_rolling1', 'FactorMin216_mean_div_std_re', 'Ret10Max_SR5', 'WAPResistBackStd_13h',
                'sistdwfiavg_re', 'DIFMaxPct_1_5', 'FactorMin361_mean_div_std_re', 'FactorMin227_meandivstd', 'FactorMin50_diff_div_std'
                ]
