# @Time : 2021/5/7 19:28
# @Author : Zhichen Lu
# @File : factor_loading_problem.py

from dataApi.FixFactorRollPrepare import FixFactorRollPrepare

initial_param = {'start_date': 20200619, 'end_date': 20210429, 'freq': 7, 'model_time_len': 1,
                 'factor_list': ['AbnormalPriceDiff', 'AggressionNMean_1_1', 'AggressionNRank_5_1', 'AggressionNRank_5_5', 'AggressionPRaw_3_5', 'AmtPct_Mean_1',
                                 'AvgPriceVwapRateSharpe5d', 'BAStrength', 'BSPowerSkew3mean', 'BestWorstReSharpe5d', 'Beta300', 'Beta500d3', 'CGO', 'CRCS_raw_rank_ms10',
                                 'CSAD5mean', 'Close2BarHigh', 'Close2High', 'CloseExcessPercent_1', 'CloseSkew_Mean_5', 'CloseVolumeCorrBias20d', 'CloseVwapRetSkew',
                                 'ConsRetStd3std', 'Cor300Down5mean', 'Cor500D3', 'CorPV5', 'CorrAbsWRPrice5min', 'CorrAmpAmt_1', 'CorrAmpAmt_5', 'CorrAmpRet_5', 'CorrAmpVwap_1',
                                 'CorrAmpVwap_5', 'CorrCloseVol_Mean_1', 'CorrExcessRank2', 'CorrHighLowAvgToAmt_Mean_1', 'CorrHighLowAvgToAmt_Mean_5', 'CorrMaxRePriceRank',
                                 'CorrPVLowLiquidity', 'CorrRetVol_5', 'CorrVWAPBollingUpDown', 'CorrVWAPTrendHigh', 'CorrVwapVol_1', 'CorrVwapVol_5', 'CorrWRPriceRank',
                                 'DIFDifSr_1_5', 'DIFMeanRaw_5_5', 'DIFMeanRegbeta_5_30', 'DIFSkewMean_1_1', 'DIFSkewMean_5_5', 'DIFSkewRank_5_1', 'DIFStdSr_5_1', 'DisNMean_1',
                                 'DisNRaw_5', 'DisNRegbeta_5', 'DisPRaw_5', 'DisPSr_1', 'DivergWinLossRKurtRegrmse_5_5', 'DivergWinLossRMeanRank_5_5', 'DivergWinLossRMeanStd_5_5',
                                 'DivergWinLossRSkewRegrmse_5_5', 'DivergWinLossRStdRegbeta_5_15', 'DivergWinLossRStdRegrmse_5_5', 'DivergWinLossRStdStd_5_15', 'DrawdownSkew',
                                 'EVolChgBetaAbs_1_1', 'Excess300High5', 'Excess500High5', 'ExcessBollingUpRateMean5d', 'FIX_lly_12', 'FIX_lly_8', 'FSmartMax', 'FSmartMin', 'FWRM',
                                 'FWRMin', 'FactorAlpha007', 'FactorAlpha024', 'FactorAlpha024dif', 'FactorAlpha027', 'FactorAlpha040mean', 'FactorMin13_mean',
                                 'FactorMin143_meandivstd', 'FactorMin14_diff', 'FactorMin150_diff', 'FactorMin155_meandivstd', 'FactorMin163_mean', 'FactorMin164_mean',
                                 'FactorMin165_mean', 'FactorMin193_mean_re', 'FactorMin193_std', 'FactorMin1_diff_div_std', 'FactorMin217_mean_re', 'FactorMin285_std_re',
                                 'FactorMin33_mean', 'FactorMin33_std', 'FactorMin343_mean_re', 'FactorMin343_self_re', 'FactorMin359_mean_div_std_re', 'FactorMin35_diff',
                                 'FactorMin35_std', 'FactorMin383_mean_div_std_re', 'FactorMin384_mean_re', 'FactorMin3_std', 'FactorMin403_mean_re',
                                 'FactorMin405_mean_div_std_re', 'FactorMin405_std_re', 'FactorMin409_mean_div_std_re', 'FactorMin412_mean_div_std_re', 'FactorMin42_mean',
                                 'FactorMin430_mean_div_std_re', 'FactorMin450_mean_re', 'FactorMin453_std_re', 'FactorMin53_mean_div_std', 'FactorMin6_mean', 'FactorMin76_mean',
                                 'FactorMin81_std', 'FactorMin82_mean', 'FactorMin87_diff', 'FactorMin93_diff', 'FactorMinKdayShortCut_regrmse', 'FactorMinKdayShortCut_std',
                                 'FactorMinVaR_regrmse_05_10', 'Factor_Fix_zhy_101', 'Factor_Fix_zhy_208', 'Factor_Fix_zhy_66', 'GTJA14_std5', 'GTJA16_min5', 'GTJA17_bias5',
                                 'GTJA2', 'GTJA20_std5', 'GTJA32', 'GTJA41', 'GTJA62', 'GTJA8', 'GTJA8_mean5', 'HFPSCorr', 'HFPSCorrBias', 'HFPSCorrMinAdj', 'HFPSCorrStdAdj',
                                 'HFPTSCorrBias', 'HFPTSCorrStdAdj', 'HFPVCorr', 'HFPVCorrBias', 'HFPVCorrMinAdj', 'HFPVCorrStdAdj', 'HF_Amt10mSkew20d', 'HF_AmtDeg1',
                                 'HF_AmtStdStrengthCloseBias', 'HF_AmtStdStrengthCloseChange_13h', 'HF_AmtStrengthCloseChange_13h', 'HF_AmtVolatilityPriceCorr_13h',
                                 'HF_CorrMaxVolumeZScore_13h', 'HF_HighVwapSkew_13h', 'HF_Hl2OStrength_13h', 'HF_HmL2CVwapCorrZscore_13h', 'HF_HmL2CVwapCorr_13h',
                                 'HF_IlliqShortcut_13h', 'HF_LDeg1_13h', 'HF_LowHighStdRatio_13h', 'HF_MeanIntradayReturnAcrossLosingInvestors_13h', 'HF_NormRePriceCorrSharpe_13h',
                                 'HF_OpenVwapSkew', 'HF_RSRS', 'HF_RSRSZScore', 'HF_RetHHIZscore', 'HF_RetTopVwapAmtCorrBias', 'HF_UpRetAmtSkew', 'HF_VmL2HmVStdRatio',
                                 'HF_VmL2HmVStdRatio10minBias', 'HF_VolumeStrengthCloseStdBias', 'HF_VolumeStrengthDeg1', 'HF_VolumeTopVwapRatio',
                                 'HF_VwapAmtUpCorrInLowVolatility_13h', 'HF_VwapBollingUp_13h', 'HF_VwapHighStdVolumeRatioZscore_13h', 'HF_VwapLowVR_13h',
                                 'HF_VwapStdSwingCorrZscore_13h', 'HF_VwapTailVolumeRatio_13h', 'HF_VwapTopTailAmtRatio_13h', 'HF_VwapTopTailTurnRatioZscore',
                                 'HF_VwapTopTailVolumeStdRatio_13h', 'HF_VwapTopTailVolume_13h', 'HF_VwapTopVolumeRatioZscore_13h', 'HLLength5', 'HLOKurt3', 'HLStd1mean',
                                 'HLStdRatio', 'HfHalfDayCloseRtnCountDiffBias_13h', 'HfHalfDayCloseRtnCountDiff_13h', 'HfLast120HighLowDiffAmtCloseCorrPreBias',
                                 'HfLast120LongTurnSkew_13h', 'HfLast120MaxRtnCloseCorrBias_13h', 'HfLast120MinRtnCloseCorrSharpe', 'HfLast120RtnPerAmtVolCorr',
                                 'HfLast60TurnVolCorr', 'HfLongVwapSwingCorr5d', 'HfLongVwapSwingCorrBias', 'HfRtnPerAmtVolCorr', 'HfSwingCloseCorr', 'HfTopRtnVolumeRatioMean',
                                 'HfVolSkew', 'High2LowVolDown', 'High2Low_5', 'HighCloseDistance', 'HighFreqDownSpeed', 'HighFreqDrawBackMeanBias', 'HighFreqDrawBackStdBias',
                                 'HighFreqHighMARetCorr', 'HighFreqRelativeClose', 'HighFreqSwingStdCmp', 'HighFreqVHFCorrBias', 'HighLowMeanVwapRetSharpe',
                                 'HighLowStdLowDistance10d', 'HighLowVwapDiffStdRatio', 'HighLowVwapRatio', 'HighSkew_Mean_5', 'IdeaVStdL_mean10', 'IdealRev2',
                                 'IndustryExcessPVCorrBias5d', 'L2C5', 'LargeSmallVolumeVWAPRatio', 'Last30MaxDrawdownBias20d', 'Last30minReVolumeCorrMean5d', 'LatestRetRatio',
                                 'LiqUp5', 'LogAmt_1', 'LogAmt_5', 'LogDeltaVol_meandivstd10', 'LogFreeTurn_1', 'LogFreeTurn_5', 'LogRtn2Amt5', 'LowSharpeAmountStdRatio',
                                 'LowStdRatio_max5', 'MACDEChgStd_5_1', 'MACDNumDiff_5_5', 'MaxDrawDown', 'MeanRatio_min5', 'MinCapitalGainAbs', 'MinCapitalGainBetaEwm',
                                 'MinCapitalGainBetaZscore', 'MinCapitalGainOverhang', 'MinCapitalGainRH', 'MinCorrAbsRePriceRank2D', 'MinCorrExcessPriceRank',
                                 'MinCorrVolumePrice_1', 'MinDailyCorrCloseVol', 'MinDailyCorrCloseVol_min5', 'MinDirectedVol', 'MinExtremRet', 'MinMaxRet', 'MinPVCorr',
                                 'MinPre30mAutoCorr', 'MinPre30mAutoCorrDelta', 'MinPre5mSkew', 'MinPreTopVolRate', 'MinVwapHLRateBetaBias', 'MinVwapHLRateBetaDelta',
                                 'MinuteTVRtnRank', 'MinuteVolatilityPriceCorr', 'NetworkDegree3', 'NetworkDegree3Net', 'NetworkPremium3', 'OTC5std', 'OverBuySellSkewRegbeta_5_5',
                                 'OverflowPerAmtMean5d', 'PDSS', 'PVSwingCorr', 'PriceDeviationBias10d', 'PriceRange_5', 'PriceSkew', 'PriceUpDownRatio', 'RSIMeanRegbeta_5_15',
                                 'RSIMeanRegrmse_1_15', 'RSIMinMean_1_15', 'RSIStdRank_5_5', 'RSRS_Mean_1', 'RS_mean', 'ReLow_13h', 'Ret30Mean2Std_10', 'Ret30RankMean_5',
                                 'RetAdjVolMaxMean_1_5', 'RetAdjVolMeanRank_3_5', 'RetAdjVolMeanSkew_1_5', 'RetAdjVolMeanSr_1_5', 'RetAdjVolSkewRaw_1_1',
                                 'RetAdjVolSkewRegbeta_5_5', 'RetBigStdResAmt5', 'RetGather0p9mean5', 'RetTurnCorr', 'RetUpSR', 'RetUpWeightedByVolSR', 'RetVolCVMultiple',
                                 'RetVolMeanSr_1_1', 'RetVolSkewMean_1_5', 'RevExclu4mean', 'RollingCloseOpenWeightedCorr_10', 'RollingCorrCloseVolume', 'Rtn2VolumeStd5',
                                 'SharpeDuringAmountDrop', 'SharpeDuringStdDrop', 'ShortTurn', 'SignDownWick', 'SignedVolume', 'SplitVolumeStdDownRatio', 'StdAmountDiff',
                                 'StdHmL_20', 'StdUpDown', 'SwingPriceCorr', 'TemporalVolumePriceCorr', 'TopAmountRatioVolumeDiffSharpe', 'TrendStrength', 'TurnHighKurtRollingStd',
                                 'TurnStd', 'TurnStdPure3mean', 'TurnStdPure5std', 'TurnWeiRet10slope', 'TurnWeiRet3mean', 'TurnWeiRet3min', 'TurnWeiRet5min', 'TwapSkewToVwap',
                                 'UDContrast5mean', 'UpDownAmtRatioKurtSr_5_5', 'UpDownAmtRatioStdMean_1_5', 'UpDownVolRatioStdRaw_1_1', 'UpDownVolRatioStdRegbeta_5_1',
                                 'UpDownVolRatioStdRegbeta_5_5', 'UpToRetValue', 'VHighKurt', 'VNSPMean_1_5', 'VarResampleMean_max10', 'VolChg1Mean', 'VolMeanSharpeUp_13h',
                                 'VolSharpeUp_13h', 'VolSkew', 'VolaDownward20', 'VolumeDownChange_13h', 'VolumeMax10min2All_13h', 'VwapAmtCorrMean5d_13h',
                                 'VwapStdCorrBias20d_13h', 'VwapStdCorrDistanceLow10d_13h', 'VwapSwingCorr', 'VwapmaLowDiffSkew_13h', 'WAPResistBackRatio_13h',
                                 'WAPResistBackStd_13h', 'WL350_5', 'WR2d_13h', 'WRMean5d_13h', 'WR_13h', 'WeightedFlow_1', 'WilliamUp_diffstd5', 'WilliamsIndicator_13h',
                                 'WilliamsPriceVolCorrMultiple_13h', 'adjEMAbc_intraday5', 'adjdmstdcpt_intraday_5', 'adjstdsd_intraday_5', 'adjstdstm_intraday_5',
                                 'adjstdwms_intraday_5', 'amtavg_mktstate_amt_std_topskew_5_3', 'amtavg_ntdmkurt_20_10', 'amtavg_ntdmkurt_60_10', 'amtkrt_ntrdmmean_20_10',
                                 'amtkrt_ntrdmmean_60_10', 'cummaxdd_ntmaxstd_20_3', 'cummaxdd_nttrbmean_20_10', 'cummaxdd_nttrbmean_20_3', 'dailyms_intraday_5',
                                 'dretvolnew_bwkurtmean_20_10', 'dretvolnew_bwmeanskew_20_10', 'dretvolnew_bwskewmean_20_3', 'dretvolnew_ntdmstd_60_10',
                                 'dretvolnew_ntkurtmean_20_10', 'dretvolnew_ntkurtskew_20_10', 'dretvolnew_ntrdmmean_60_3', 'dretvvolnew_bwmeanskew_60_10',
                                 'dretvvolnew_bwstdkurt_60_10', 'dretvvolnew_ntmeanskew_60_10', 'dretvvolnew_ntskewmean_20_10', 'dretvvolnew_ntstdkurt_20_10',
                                 'hfCPVCorrHDmean_13h', 'hfDownPVcorr5', 'hfDownPVcorrbias', 'hfDownStrength', 'hfHVR5', 'hfHighVolPVcorr5', 'hfIdxCorr', 'hfIdxCorr5',
                                 'hfLowCapRetMin', 'hfMktLSCapMR5', 'hfMktLSCapSR', 'hfPVcorrHD', 'hfRST', 'hfTurnSharpeHD', 'hfUpRRCbias', 'sistdwfiavg2_3_re', 'sistdwfiavg_re',
                                 'subrr2adjwms_intraday_5', 'subrradjwms_intraday_5', 'uretvolnew_ntdmstd_20_10', 'uretvvolnew_ntdmkurt_20_10', 'uretvvolnew_ntmsmean_20_10',
                                 'zhy_fix_146', 'zhy_fix_5'], 'load_address': '/data/group/800319/HFfactor/RealTimeFixRollRobust/data/'}
loading_param = {'end_date': 20210429, 'return_idx': True, 'start_date': 20200619}
dp = FixFactorRollPrepare(**initial_param)
res = dp.load_data(**loading_param)
