# @Time : 2020/6/1 9:39
# @Author : Zhichen Lu
# @File : factor_definition.txt.py


alpha1 = - ts_corr(cross_rank(delta(np.log(vol))), cross_rank(close / open), 10)
alpha2 = - delta((2 * close - high - low) / (high - low))
alpha3 = - ts_sum(np.where(close == delay(close), 0, close - np.where(close > delay(close), np.fmin(low, delay(close)), np.fmax(high, delay(close)))), 6)
alpha4 = ts_sum(np.where(ts_mean(close, 8) + ts_std(close, 8) < ts_mean(close, 2), -1,
                         np.where(ts_mean(close, 8) - ts_std(close, 8) > ts_mean(close, 2), 1, np.where((vol / ts_mean(vol, 20) >= 1), 1, -1))), 10)
alpha5 = - ts_max(ts_corr(ts_rank(vol, 5), ts_rank(high, 5), 10), 3)
alpha6 = - cross_rank(ts_sum(np.sign(delta(0.85 * open + 0.15 * high, 4)), 10))
alpha7 = (cross_rank(ts_max(vwap - close, 3)) + cross_rank(ts_min(vwap - close, 3))) * cross_rank(delta(vol, 3))
alpha8 = - cross_rank(delta(0.1 * high + 0.1 * low + 0.8 * vwap, 10))
alpha9 = - ts_ewm(delta((high + low) / 2) * (high - low) / vol, 5, 0.7)
alpha10 = - cross_rank(np.fmax(np.where(ret < 0, ts_std(ret, 20), close) ** 2, 5))
alpha11 = - ts_sum((2 * close - high - low) / (high - low) * np.log(vol), 6)
alpha12 = - cross_rank(open - ts_mean(vwap, 10)) * cross_rank(np.abs(close - vwap))
alpha13 = ts_mean(np.sqrt(high * low) - vwap, 30)
alpha14 = - delta(close, 5)
alpha16 = - ts_max(cross_rank(ts_corr(cross_rank(vol), cross_rank(vwap), 5)), 5)
alpha17 = - cross_rank(vwap - ts_max(vwap, 15)) * delta(close, 5)
alpha18 = - close / delay(close, 5)
alpha19 = - np.where(close < delay(close, 5), close / delay(close, 5) - 1, 1 - delay(close, 5) / close)
alpha21 = - ts_beta(close, sequence, 6)
alpha22 = - ts_ewm(delta(close / ts_mean(close, 6), 3), 10, 0.8)
alpha23 = - ts_ewm(np.where(close > delay(close), ts_std(close, 20), 0), 10, 0.9) / ts_ewm(ts_std(close, 20), 10, 0.9)
alpha24 = - ts_ewm(delta(close, 5), 10, 0.8)
alpha25 = - cross_rank(delta(close, 7) * (1 - cross_pct(ts_decaylinear(vol / ts_mean(vol, 20), 9)))) * (1 + cross_pct(ts_sum(ret, 20)))
alpha27 = - ts_decaylinear(close / delay(close, 3) + close / delay(close, 6), 12)
alpha28 = - 3 * ts_ewm((close - ts_min(low, 9)) / ts_max(high, 9), 5, 0.66) + 2 * ts_ewm(ts_ewm((close - ts_min(low, 9)) / ts_max(high, 9), 5, 0.66), 5, 0.66)
alpha29 = - (close / delay(close, 6) - 1) * np.log(vol)
alpha31 = - close / ts_mean(close, 12)
alpha32 = - ts_sum(cross_rank(ts_corr(cross_rank(high), cross_rank(vol), 5)), 5)
alpha35 = - np.fmin(cross_rank(ts_decaylinear(delta(open), 15)), cross_rank(ts_decaylinear(ts_corr(vol, open, 17), 7)))
alpha36 = - cross_rank(ts_sum(ts_corr(cross_rank(vol), cross_rank(vwap), 10), 2))
alpha37 = - cross_rank(delta(ts_sum(open, 5) * ts_sum(ret, 5), 10))
alpha38 = ts_mean(np.where(ts_mean(high, 10) < high, - delta(high, 2), 0), 10)
alpha39 = - cross_rank(ts_decaylinear(delta(close, 2), 8)) - cross_rank(ts_decaylinear(ts_corr(0.3 * vwap + 0.7 * open, ts_sum(ts_mean(vol, 8), 2), 10), 10))
alpha40 = - ts_sum(np.where(close > delay(close), vol, 0), 20) / ts_sum(np.where(close <= delay(close), vol, 0), 20)
alpha41 = - cross_rank(ts_max(delta(vwap, 3), 5))
alpha42 = - cross_rank(ts_std(high, 10)) * ts_corr(high, vol, 10)
alpha43 = - ts_sum(np.where(close > delay(close), vol, np.where(close < delay(close), - vol, 0)), 6)
alpha45 = - cross_rank(delta(0.4 * close + 0.6 * open)) * cross_rank(ts_corr(vwap, ts_mean(vol, 25), 5))
alpha46 = (ts_mean(close, 3) + ts_mean(close, 6) + ts_mean(close, 12) + ts_mean(close, 24)) / close
alpha47 = ts_ewm((ts_max(high, 6) - close) / (ts_max(high, 6) - ts_min(low, 6)), 10, 0.91)
alpha48 = - cross_rank(np.sign(delta(close)) + np.sign(delay(close) - delay(close, 2)) + np.sign(delay(close, 2) - delay(close, 3))) * ts_sum(vol, 5) / ts_sum(vol, 20)
alpha49 = ts_sum(np.where(high + low >= delay(high) + delay(low), 0, np.fmax(np.abs(delta(high)), np.abs(delta(low)))), 12) / ts_sum(
    np.fmax(np.abs(delta(high)), np.abs(delta(low))), 12)
alpha50 = (ts_sum(np.where(high + low >= delay(high) + delay(low), 0, np.fmax(np.abs(delta(high)), np.abs(delta(low)))), 12) - ts_sum(
    np.where(high + low <= delay(high) + delay(low), 0, np.fmax(np.abs(delta(high)), np.abs(delta(low)))), 12)) / ts_sum(np.fmax(np.abs(delta(high)), np.abs(delta(low))), 12)
alpha52 = - ts_sum(np.fmax(0, high - delay((high + low + close) / 3)), 26) / ts_sum(np.fmax(0, delay((high + low + close) / 3) - low), 26)
alpha53 = - ts_sum(close > delay(close), 12)
alpha55 = - ts_sum((delta(close) + (close - open) / 2 + delay(close) - delay(open)) / np.where(
    (np.abs(high - delay(close)) > np.abs(low - delay(close))) & (np.abs(high - delay(close)) > np.abs(high - delay(low))),
    np.abs(high - delay(close)) + np.abs(low - delay(close)) / 2 + np.abs(delay(close) - delay(open)) / 4,
    np.where((np.abs(low - delay(close)) > np.abs(high - delay(low))) & (np.abs(low - delay(close)) > np.abs(high - delay(low))),
             np.abs(low - delay(close)) + np.abs(high - delay(close)) / 2 + np.abs(delay(close) - delay(open)) / 4,
             np.abs(high - delay(low)) + np.abs(delay(close) - delay(open)) / 4)) * np.fmax(np.abs(high - delay(close)), np.abs(low - delay(close))), 20)
alpha56 = cross_rank(open - ts_min(open, 12) - cross_rank(ts_corr(ts_sum((high + low) / 2, 19), ts_sum(ts_mean(vol, 40), 19), 13)))
alpha57 = - ts_ewm((close - ts_min(low, 9)) / (ts_max(high, 9) - ts_min(low, 9)), 10, 0.67)
alpha58 = - ts_sum(close > delay(close), 20)
alpha59 = - ts_sum(np.where(close == delay(close), 0, close - np.where(close > delay(close), np.fmin(low, delay(close)), np.fmax(high, delay(close)))), 20)
alpha60 = - ts_sum((2 * close - high - low) / (high - low) * vol, 20)
boll1 = - alpha1 / ts_std(alpha1, 20)
boll2 = - alpha / ts_std(alpha, 20)
boll3 = - (alpha1 - ts_mean(alpha1, 20)) / ts_std(alpha1, 20)
boll4 = - (alpha - ts_mean(alpha, 20)) / ts_std(alpha, 20)
boll5 = - alpha1 + ts_min(ts_mean(alpha1, 5), 20)
boll6 = - alpha + ts_min(ts_mean(alpha, 5), 20)
boll7 = - (alpha1 - ts_min(ts_mean(alpha1, 5), 20)) / ts_std(alpha1, 10)
boll8 = - (alpha - ts_min(ts_mean(alpha, 5), 20)) / ts_std(alpha, 10)
boll9 = - alpha1 + ts_max(ts_mean(alpha1, 5), 20)
boll10 = - alpha + ts_max(ts_mean(alpha, 5), 20)
boll11 = - (alpha1 - ts_max(ts_mean(alpha1, 5), 20)) / ts_std(alpha1, 10)
boll12 = - (alpha - ts_max(ts_mean(alpha, 5), 20)) / ts_std(alpha, 10)
factor63 = -1 * ts_ewm(np.fmax(close - delay(close, 5), 0), 20) / ts_ewm(abs(close - delay(close, 5)), 20) * 100
factor98 = ((((delta((ts_sum(close, 30) / 30), 30) / delay(close, 30)) <= 0.03)) * (-1 * (close - delay(ts_min(close, 30), 1))) + ~(
((delta((ts_sum(close, 30) / 30), 30) / delay(close, 30)) <= 0.03)) * (-1 * delta(close, 5)))
factor118 = ts_sum(ts_max(high, 5) - close, 20) / ts_sum(close - ts_min(low, 5), 20)
factor72 = ts_ewm((ts_max(high, 6) - close) / (ts_max(high, 6) - ts_min(low, 6)) * 100, 20)
factor107 = -1 * cross_rank((open / open[0] - delay(high / open[0], 10))) * cross_rank((open / open[0] - delay(close / open[0], 10))) * cross_rank(
    (open / open[0] - delay(low / open[0], 10)))
factor69 = -1 * (ts_sum(dtm, 20) > ts_sum(dbm, 20)) * ((ts_sum(dtm, 20) - ts_sum(dbm, 20)) / ts_sum(dtm, 20)) + (~(ts_sum(dtm, 20) > ts_sum(dbm, 20))) * (
            (ts_sum(dtm, 20) == ts_sum(dbm, 20)) * 0 + (~((ts_sum(dtm, 20) == ts_sum(dbm, 20))) * ((ts_sum(dtm, 20) - ts_sum(dbm, 20)) / ts_sum(dbm, 20))))
factor114 = (cross_rank(delay(((ts_max(high, 10) - ts_min(low, 10)) / ts_mean(close, 20)), 5)) * cross_rank(ts_sum(vol, 10))) / (
            ((ts_max(high, 10) - ts_min(low, 10)) / ts_mean(close, 20)) / (ts_sum(amt, 10) / ts_sum(vol, 10) - close))
factor68 = -1 * ts_ewm(((high + low) / 2 - (delay(high, 10) + delay(low, 10)) / 2) * (high - low) / amt, 20)
factor99 = (-1 * cross_rank(ts_corr(cross_rank(close), cross_rank(vol), 20) * ts_std(close, 20) * ts_std(vol, 20)))
factor113 = -1 * ((cross_rank((ts_sum(delay(close, 5), 20) / 20)) * ts_corr(close, vol, 20)) * cross_rank(ts_corr(ts_sum(close, 5), ts_sum(close, 5), 20)))
factor64 = -1 * (np.fmax(cross_rank(ts_decaylinear(ts_corr(cross_rank(vwap), cross_rank(vol), 20), 5)),
                         cross_rank(ts_decaylinear(ts_max(ts_corr(cross_rank(close), cross_rank(ts_mean(vol, 5)), 20), 10), 10))) * 1)
factor105 = -1 * ts_corr(cross_rank(close), cross_rank(vol), 20)
factor90 = -1 * cross_rank(ts_corr(cross_rank(vwap / vwap[0]), cross_rank(ts_mean(vol, 5) / ts_mean(vol, 5)[4]), 20))
factor62 = -1 * ts_corr(low, cross_rank(vol), 20)
factor91 = -1 * ((cross_rank((close - delay(ts_max(close, 5), 1))) * cross_rank(ts_corr((ts_mean(vol, 5)), low, 20))) - 1)
factor83 = (-1 * cross_rank(ts_corr(cross_rank(high), cross_rank(vol), 20) * ts_std(cross_rank(high), 20) * ts_std(cross_rank(vol), 20)))
factor101 = -1 * cross_rank(ts_corr(close, ts_sum(ts_mean(vol, 5), 5), 20))
factor73 = ((ts_rank(ts_decaylinear(ts_decaylinear(ts_corr(close, vol, 10), 5), 5), 10) - cross_rank(ts_decaylinear(ts_corr(vwap, ts_mean(vol, 10), 10), 5))) * 1)
factor119 = -1 * (cross_rank(ts_decaylinear(ts_corr(ts_sum(amt, 10) / ts_sum(vol, 10), ts_sum(ts_mean(vol, 5), 5), 20), 5)) - cross_rank(
    ts_decaylinear(ts_rank(ts_min(ts_corr(cross_rank(delay(open, 5)), cross_rank(ts_mean(vol, 5)), 20), 5), 15), 5)))
factor74 = -1 * (cross_rank(ts_corr(ts_sum(((low * 0.35) + (vwap * 0.65)), 10), ts_sum(ts_mean(vol, 5), 10), 10)) + cross_rank(ts_corr(cross_rank(vwap), cross_rank(vol), 10)))
factor_dev04 = -close / ts_cummean(close)
factor81 = -1 * ts_ewm(vwap / vwap[0], 20)
factor_dev02 = -1 * (alpha - ts_min(ts_mean(alpha, 5), 20))
factor120 = (cross_rank((vwap / close[0] - close / close[0])) / cross_rank((vwap / close[0] + close / close[0])))
factor106 = -1 * close / delay(close, 20)
factor_dev05 = -close / ts_mean(close, 20)
factor_dev07 = -1 * (alpha - ts_mean(alpha, 20))
factor86 = -1 * ts_mean(close, 20) / delay(ts_mean(close, 20), 10)
factor106 = -1 * vwap / delay(vwap, 20) - 1
factor78 = -1 * ((high + low + close) / 3 - ts_mean((high + low + close) / 3, 20)) / (ts_mean(abs(close - ts_mean((high + low + close) / 3, 20)), 20))
factor_dev03 = -1 * (alpha - ts_max(ts_mean(alpha, 5), 20))
factor_dev08 = -1 * (close - ts_min(ts_mean(close, 5), 20))
factor71 = -1 * (vwap - ts_mean(vwap, 20)) / ts_mean(vwap, 20)
factor_dev01 = -1 * (close - ts_max(ts_mean(close, 5), 20))
factor61 = -1 * np.fmax(cross_rank(ts_decaylinear(delta(vwap, 5), 5)), cross_rank(ts_decaylinear(cross_rank(ts_corr((high), ts_mean(vol, 5), 20)), 5)))
factor116 = -1 * ts_beta(close, np.array([[[x for x in range(242)] for i in range(close.shape[1])] for j in range(close.shape[2])]).transpose(2, 1, 0), 20)
factor110 = -1 * ts_sum(np.fmax(0, high - delay(close, 5)), 20) / ts_sum(np.fmax(0, delay(close, 1) - low), 20) * 100
factor87 = -1 * (cross_rank(ts_decaylinear(delta(vwap, 5), 15)) + ts_rank(ts_decaylinear(((((low * 0.9) + (low * 0.1)) - vwap) / (open - ((high + low) / 2))), 5), 20))
factor92 = -1 * np.fmax(cross_rank(ts_decaylinear(delta(((close * 0.35) + (vwap * 0.65)), 5), 5)), ts_rank(ts_decaylinear(abs(ts_corr((ts_mean(vol, 5)), close, 20)), 5), 15))
factor103 = -1 * ((20 - ts_argmax(ts_max(high, 5), 20) + 1) / 20) * 100
factor75 = -1 * ts_sum((close > delay(open, 10)) * (benchmarkindexclose < delay(benchmarkindexopen, 10)) * 1, 20) / ts_sum(
    (benchmarkindexclose < delay(benchmarkindexopen, 10)) * 1, 20)
factor94 = -1 * ts_sum(((close > delay(close, 5)) * vol + (close < delay(close, 5)) * (-vol)), 20)
factor112 = -1 * ((ts_sum((close - delay(close, 5) > 0) * (close - delay(close, 5)), 20) - ts_sum((close - delay(close, 5) < 0) * abs(close - delay(close, 5)), 20)) / (
            ts_sum((close - delay(close, 5) > 0) * (close - delay(close, 5)), 20) + ts_sum((close - delay(close, 5) < 0) * abs(close - delay(close, 5)), 20)) * 100)
alpha122 = -(ts_ewm(ts_ewm(ts_ewm(np.log(close), 13), 13), 13) - delay(ts_ewm(ts_ewm(ts_ewm(np.log(close), 13), 13), 13), 1)) / delay(
    ts_ewm(ts_ewm(ts_ewm(np.log(close), 13), 13), 13), 1)
alpha123 = -cross_pct(ts_corr(ts_sum((high + low) / 2, 20), ts_sum(ts_mean(vol, 30), 20), 20))
alpha124 = -cross_pct((close - vwap) / ts_ewm((ts_max(close, 30)), 10))
alpha126_1 = (close + ts_cummax(high) + ts_cummin(low)) / close
alpha126_2 = -cross_pct((close + high + low) / ts_mean(close + high + low, 10))
alpha127 = -ts_mean(100 * (close - ts_max(close, 10)) / ts_max(close, 10) ** 2, 10)
alpha129 = -ts_sum(np.where(close > delay(close - 1), abs(close - delay(close, 1)), 0), 10)
alpha133_1 = -cross_pct(ts_argmin(low, 20) - ts_argmax(high, 20))
alpha133_2 = cross_pct(ts_argcummin(low) - ts_argcummax(high))
alpha134 = -cross_pct((close - delay(close, 10)) / delay(close, 10) * vol)
alpha135 = -ts_ewm(delay(close / delay(close, 20), 1), 20)
alpha139 = cross_pct(-1 * ts_corr(close, vol, 10))
alpha140 = -cross_pct(ts_decaylinear(cross_pct(open) + cross_pct(low) - cross_pct(high) + cross_pct(close), 8))
alpha141 = -cross_pct(ts_corr(cross_pct(high), cross_pct(ts_mean(vol, 15)), 9))
alpha142 = -1 * cross_pct(ts_rank(close, 10)) * cross_pct(delta(delta(close, 1), 1)) * cross_pct(ts_rank(vol / ts_mean(vol, 20), 5))
alpha145 = (ts_mean(vol, 10) - ts_mean(vol, 30)) / ts_mean(vol, 20)
alpha147 = -ts_beta(ts_mean(close, 12), np.arange(close.shape[0]).repeat(close.shape[1] * close.shape[2]).reshape(close.shape), 30)
alpha151 = -ts_ewm(close - delay(close, 20), 20)
alpha153 = (ts_mean(close, 3) + ts_mean(close, 6) + ts_mean(close, 12) + ts_mean(close, 24)) / close
alpha156 = -(np.fmax(cross_pct(ts_decaylinear(delta(vwap, 5), 3)), cross_pct(ts_decaylinear(delta((open * 0.15) + (low * 0.85), 2) / ((open * 0.15) + (low * 0.85)) - 1, 3))) - 1)
alpha161 = -ts_mean(np.fmax(np.fmax(high - low, abs(delay(close, 1) - high)), abs(delay(close, 1) - low)), 12)
alpha163 = cross_pct(-1 * (close / delay(close, 1) - 1) * ts_mean(vol, 20) * vwap * (high - close))
alpha164 = cross_pct(ts_ewm(np.where(close > delay(close, 1), 1 / (close - delay(close, 1) + 1), 1) / (high - low + 1) * 100, 13))
alpha166 = cross_pct(
    -20 * 19 ** 1.5 * ts_sum(close / delay(close, 1) - 1 - ts_mean(close / delay(close, 1) - 1, 20), 20) / (19 * 18 * ts_sum(close / delay(close, 1) ** 2, 20) ** 1.5))
alpha167 = -ts_sum(np.where(close - delay(close, 1) > 0, close - delay(close, 1), 0), 12)
alpha168 = vol / ts_mean(vol, 20)
alpha169 = -ts_ewm(ts_mean(delay(ts_ewm(close - delay(close, 1), 9), 1), 12) - ts_mean(delay(ts_ewm(close - delay(close, 1), 9), 1), 26), 10)
alpha170 = cross_pct(1 / close) * vol / ts_mean(vol, 20) * high * cross_pct(high - close) / (ts_sum(high, 5) / 5) - cross_pct(vwap - delay(vwap, 5))
alpha171 = -cross_pct(-1 * (low - close) * (open ** 5) / ((close - high) * (close ** 5) + 1))
alpha174 = -ts_ewm(np.where(close > delay(close, 1), ts_std(close, 20), 0), 20)
alpha180 = cross_pct(np.where(ts_mean(vol, 20) < vol, -ts_rank(abs(delta(close, 7)), 60) * np.sign(delta(close, 7)), -vol))
alpha181 = -ts_sum(close / delay(close, 1) - 1 - ts_mean(close / delay(close, 1) - 1, 20), 20)
alpha184 = cross_pct(cross_pct(ts_corr(delay(open - close, 1), close, 20)) + cross_pct(open - close))
alpha187 = -ts_sum(np.where(open <= delay(open, 1), 0, np.fmax(high - open, open - delay(open, 1))), 20)
alpha188 = cross_pct((high - low - ts_ewm(high - low, 11)) / ts_ewm(high - low, 11))
alpha189 = -ts_mean(abs(close - ts_mean(close, 6)), 6) / close
alpha191 = -ts_corr(ts_mean(vol, 20), low, 5) + (high + low) / (2 * close)
alpha175 = - ts_mean(np.fmax(np.fmax(high - low, np.abs(delay(close) - high)), np.abs(delay(close) - low)), 6)
alpha176 = - ts_corr(cross_rank((close - ts_min(low, 12)) / (ts_max(high, 12) - ts_min(low, 12))), cross_rank(vol), 6)
alpha177 = ts_argmax(high, 20)
alpha178 = - (close / delay(close) - 1) * vol
alpha179 = - cross_rank(ts_corr(vwap, vol, 4)) * cross_rank(ts_corr(cross_rank(low), cross_rank(ts_mean(vol, 50)), 12))
