# coding: utf-8
# Author：fengchi863
# Date ：2023/7/4 20:52

import pandas as pd
from xquant.factordata import FactorData
import numpy as np
s = FactorData()

def calc_mdd(_s):
    mdd = (np.maximum.accumulate(np.nancumsum(_s)) - np.nancumsum(_s)).max()
    return -mdd

def factor_fc_nextT1_20231130_6(start_date, end_date, IO, return_fillna_dic=False):
    import sys
    factor_name = sys._getframe().f_code.co_name[7:]

    if return_fillna_dic:
        return {factor_name: 0, 'data': ['AShareMoneyFlow']}
    # -----------------------------------------------当日机构主动买入金额近期与远期比值--------------------------------------------------------------------
    start_date_ = int(s.tradingday(str(start_date), -250)[0])
    md_data = IO.read_data([start_date_, end_date], columns=['BUY_VALUE_EXLARGE_ORDER_ACT'], alt='/data/group/800080/warehouse/prod/DATABASE/WIND/AShareMoneyFlow/AShareMoneyFlow.h5')

    b = md_data['BUY_VALUE_EXLARGE_ORDER_ACT'].unstack().rolling(40, min_periods=1).mean().stack()
    a = md_data['BUY_VALUE_EXLARGE_ORDER_ACT'].unstack().rolling(60, min_periods=1).mean().stack()

    factor_df = pd.DataFrame()
    factor_df[factor_name] = b - a
    # ---------------------------------------------------------------------------------------------------------------------
    """
    14.83 -0.039
    =====>>>> 14.833333333333334 -0.0391139544408043 117.51446653029195 912.473877430164 wj_last50_v2m1pct_lsdiff，sss_amts_5_60 0.5544，0.5121
!!!! fc_nextT1_20231130_12 0.7662006576986069
!!!! fc_nextT1_20231130_13 0.7253167156548512
    """
    return factor_df
"""
AShareMoneyFlow:
['OBJECT_ID', 'BUY_VALUE_EXLARGE_ORDER', 'SELL_VALUE_EXLARGE_ORDER',
'BUY_VALUE_LARGE_ORDER', 'SELL_VALUE_LARGE_ORDER',
'BUY_VALUE_MED_ORDER', 'SELL_VALUE_MED_ORDER', 'BUY_VALUE_SMALL_ORDER',
'SELL_VALUE_SMALL_ORDER', 'BUY_VOLUME_EXLARGE_ORDER',
'SELL_VOLUME_EXLARGE_ORDER', 'BUY_VOLUME_LARGE_ORDER',
'SELL_VOLUME_LARGE_ORDER', 'BUY_VOLUME_MED_ORDER',
'SELL_VOLUME_MED_ORDER', 'BUY_VOLUME_SMALL_ORDER',
'SELL_VOLUME_SMALL_ORDER', 'TRADES_COUNT', 'BUY_TRADES_EXLARGE_ORDER',
'SELL_TRADES_EXLARGE_ORDER', 'BUY_TRADES_LARGE_ORDER',
'SELL_TRADES_LARGE_ORDER', 'BUY_TRADES_MED_ORDER',
'SELL_TRADES_MED_ORDER', 'BUY_TRADES_SMALL_ORDER',
'SELL_TRADES_SMALL_ORDER', 'VOLUME_DIFF_SMALL_TRADER',
'VOLUME_DIFF_SMALL_TRADER_ACT', 'VOLUME_DIFF_MED_TRADER',
'VOLUME_DIFF_MED_TRADER_ACT', 'VOLUME_DIFF_LARGE_TRADER',
'VOLUME_DIFF_LARGE_TRADER_ACT', 'VOLUME_DIFF_INSTITUTE',
'VOLUME_DIFF_INSTITUTE_ACT', 'VALUE_DIFF_SMALL_TRADER',
'VALUE_DIFF_SMALL_TRADER_ACT', 'VALUE_DIFF_MED_TRADER',
'VALUE_DIFF_MED_TRADER_ACT', 'VALUE_DIFF_LARGE_TRADER',
'VALUE_DIFF_LARGE_TRADER_ACT', 'VALUE_DIFF_INSTITUTE',
'VALUE_DIFF_INSTITUTE_ACT', 'S_MFD_INFLOWVOLUME',
'NET_INFLOW_RATE_VOLUME', 'S_MFD_INFLOW_OPENVOLUME',
'OPEN_NET_INFLOW_RATE_VOLUME', 'S_MFD_INFLOW_CLOSEVOLUME',
'CLOSE_NET_INFLOW_RATE_VOLUME', 'S_MFD_INFLOW', 'NET_INFLOW_RATE_VALUE',
'S_MFD_INFLOW_OPEN', 'OPEN_NET_INFLOW_RATE_VALUE', 'S_MFD_INFLOW_CLOSE',
'CLOSE_NET_INFLOW_RATE_VALUE', 'TOT_VOLUME_BID', 'TOT_VOLUME_ASK',
'MONEYFLOW_PCT_VOLUME', 'OPEN_MONEYFLOW_PCT_VOLUME',
'CLOSE_MONEYFLOW_PCT_VOLUME', 'MONEYFLOW_PCT_VALUE',
'OPEN_MONEYFLOW_PCT_VALUE', 'CLOSE_MONEYFLOW_PCT_VALUE',
'S_MFD_INFLOWVOLUME_LARGE_ORDER', 'NET_INFLOW_RATE_VOLUME_L',
'S_MFD_INFLOW_LARGE_ORDER', 'NET_INFLOW_RATE_VALUE_L',
'MONEYFLOW_PCT_VOLUME_L', 'MONEYFLOW_PCT_VALUE_L',
'S_MFD_INFLOW_OPENVOLUME_L', 'OPEN_NET_INFLOW_RATE_VOLUME_L',
'S_MFD_INFLOW_OPEN_LARGE_ORDER', 'OPEN_NET_INFLOW_RATE_VALUE_L',
'OPEN_MONEYFLOW_PCT_VOLUME_L', 'OPEN_MONEYFLOW_PCT_VALUE_L',
'S_MFD_INFLOW_CLOSEVOLUME_L', 'CLOSE_NET_INFLOW_RATE_VOLUME_L',
'S_MFD_INFLOW_CLOSE_LARGE_ORDER', 'CLOSE_NET_INFLOW_RATE_VALU_L',
'CLOSE_MONEYFLOW_PCT_VOLUME_L', 'CLOSE_MONEYFLOW_PCT_VALUE_L',
'BUY_VALUE_EXLARGE_ORDER_ACT', 'SELL_VALUE_EXLARGE_ORDER_ACT',
'BUY_VALUE_LARGE_ORDER_ACT', 'SELL_VALUE_LARGE_ORDER_ACT',
'BUY_VALUE_MED_ORDER_ACT', 'SELL_VALUE_MED_ORDER_ACT',
'BUY_VALUE_SMALL_ORDER_ACT', 'SELL_VALUE_SMALL_ORDER_ACT',
'BUY_VOLUME_EXLARGE_ORDER_ACT', 'SELL_VOLUME_EXLARGE_ORDER_ACT',
'BUY_VOLUME_LARGE_ORDER_ACT', 'SELL_VOLUME_LARGE_ORDER_ACT',
'BUY_VOLUME_MED_ORDER_ACT', 'SELL_VOLUME_MED_ORDER_ACT',
'BUY_VOLUME_SMALL_ORDER_ACT', 'SELL_VOLUME_SMALL_ORDER_ACT', 'OPDATE',
'OPMODE']
"""