# coding: utf-8
# Author：fengchi863
# Date ：2021/3/25 11:07

factor_name_list = [
'tx_BigAmt_Yesterday',
 'SellCR',
 'tx_Up_Speed',
 'tx_Limit_to_Amt',
 'tx_Max_Speed',
 'BuySellPressure',
 'CRSP',
 'zjlx',
 'tx_WeightedAvgBuySellPx',
 'retKP',
 'IntervalLargeTrade',
 'tx_TickRet2',
 'tx_TickBuy_weight',
 'Pct10d',
 'ZtTime',
 'tx_MeanPx_Weight',
 'zdmr',
 'LargeBuyRatio',
 'UTD',
 'LnMV',
 'IntervalNetBuy',
 'IntervalLargeSell',
 'TradeCR',
 'tx_BigOrder_Weight',
 'tx_Position_High',
 'tx_Pct_Yesterday',
 'IntervalLargeBuy',
 'tx_Buy_mean_std',
 'voldiffstd10',
 'netLargeBuyRatio',
 'TurnVolStd',
 'tx_TickRet2_diff',
 'TurnVolMean',
 'tx_CorrPV_shift',
 'LargeSellRatio',
 'tx_OpenPct',
 'Pct5d',
 'LargeTradeRatio',
 'volumebodong10',
 'tx_Limit_to_Limit'
]

del_factor_list = [
 # 'tx_CorrRV',
 # 'MPC9',
 # 'VolRatio',
 # 'MPC7',
 # 'VolPerTradeRatio',
 # 'MPC2',
 # 'MPC5',
 # 'MPC8',
 # 'jqskew10',
 # 'MPC10',
 # 'AmtPerTradeRatio',
 # 'tx_CorrRV_shift',
 # 'MPC4',
 # 'MPC6',
 # 'MPC3',
 # 'MPC1',
 # 'netBidRatio',
 # 'netBidRatio_5',
 # 'LnMV',
 # 'BidRatio'
]